from config import CELL_SIZE, MAP_COLS, MAP_ROWS


MAP_WIDTH = MAP_COLS * CELL_SIZE
MAP_HEIGHT = MAP_ROWS * CELL_SIZE
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 768
MIN_WINDOW_WIDTH = 960
MIN_WINDOW_HEIGHT = 720

SIDEBAR_X = MAP_WIDTH
SIDEBAR_Y = 0

LOG_AREA_X = SIDEBAR_X + 10
LOG_AREA_Y = 200
LOG_AREA_WIDTH = 300
LOG_AREA_HEIGHT = WINDOW_HEIGHT - 210
