from config import CELL_SIZE, MAP_COLS, MAP_ROWS, SIDEBAR_WIDTH


MAP_WIDTH = MAP_COLS * CELL_SIZE
MAP_HEIGHT = MAP_ROWS * CELL_SIZE
WINDOW_WIDTH = MAP_WIDTH + SIDEBAR_WIDTH
WINDOW_HEIGHT = MAP_HEIGHT

SIDEBAR_X = MAP_WIDTH
SIDEBAR_Y = 0

LOG_AREA_X = SIDEBAR_X + 10
LOG_AREA_Y = 200
LOG_AREA_WIDTH = SIDEBAR_WIDTH - 20
LOG_AREA_HEIGHT = WINDOW_HEIGHT - 210
