from enum import Enum


class CellType(Enum):
    GATE = "G"
    ROAD = "R"
    INTERSECTION = "I"
    OBSTACLE = "X"
    BLOCKED = "B"
    PARKING_SLOT = "P"
    CAR_SLOT = "C"
    MOTO_SLOT = "M"
    EMPTY = "."


class VehicleType(Enum):
    CAR = "CAR"
    MOTORBIKE = "MOTORBIKE"


class VehicleStatus(Enum):
    WAITING = "WAITING"
    MOVING = "MOVING"
    ARRIVED = "ARRIVED"
    PARKED = "PARKED"
    MANUAL = "MANUAL"
    REROUTING = "REROUTING"
    VIOLATION = "VIOLATION"


class AlgorithmType(Enum):
    BFS = "BFS"
    DFS = "DFS"
    GREEDY = "GREEDY"
    ASTAR = "ASTAR"


class WaitReason(Enum):
    NONE = "NONE"
    BLOCKED_BY_VEHICLE = "BLOCKED_BY_VEHICLE"
    BLOCKED_BY_OBSTACLE = "BLOCKED_BY_OBSTACLE"
    TRAFFIC_CONGESTION = "TRAFFIC_CONGESTION"
    WAITING_FOR_INTERSECTION = "WAITING_FOR_INTERSECTION"
    NO_PATH = "NO_PATH"
    NO_SLOT = "NO_SLOT"
    NO_EXIT_PATH = "NO_EXIT_PATH"
    EXITING = "EXITING"
    YIELDING = "YIELDING"
    GUARD_ESCORT = "GUARD_ESCORT"
    PARKING_VIOLATION_WRONG_TYPE = "PARKING_VIOLATION_WRONG_TYPE"
    PARKING_VIOLATION_ILLEGAL_ROAD = "PARKING_VIOLATION_ILLEGAL_ROAD"
    PARKING_VIOLATION_BLOCKING_INTERSECTION = "PARKING_VIOLATION_BLOCKING_INTERSECTION"
